name: bunyan-logviewer
summary: Logviewer
description: |
      lv is a logviewer for bunyan and pino logger.
website: https://github.com/gildas/lv
source-code: https://github.com/gildas/lv
issues: https://github.com/gildas/lv/issues
license: MIT
version: 0.2.0
base: core22
grade: stable
confinement: strict

apps:
  lv:
    command: bin/lv

parts:
  lv:
    plugin:      go
    source-type: git
    source:      https://github.com/gildas/lv
    build-snaps: [go]
